# The Project API Token from Web Translate It
api_key: 'a299a9a3901da67224122660f34f0166afb12f25'

# The locales not to sync with Web Translate It.
# Pass an array of string, or an array of symbols, a string or a symbol.
# eg. [:en, :fr] or just 'en'
ignore_locales: 'en'

# A list of files to translate
# You can name your language files as you want, as long as the locale name match the
# locale name you set in Web Translate It, and that the different language files names are
# differenciated by their locale name.
# For example, if you set to translate a project in en_US in WTI, you should use the locale en_US in your app
#
# wti_id is the file id from Web Translate It.
files:
  1780: config/locales/[locale].yml